CreateThread(function()
	SetWeaponDamageModifier(`WEAPON_UNARMED`, 0.0)
	SetWeaponDamageModifier(`WEAPON_BOTTLE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_FLASHLIGHT`, 0.0)
	SetWeaponDamageModifier(`WEAPON_KNUCKLE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_NIGHTSTICK`, 0.0)
	SetWeaponDamageModifier(`WEAPON_HAMMER`, 0.0)
	SetWeaponDamageModifier(`WEAPON_CROWBAR`, 0.0)
	SetWeaponDamageModifier(`WEAPON_POOLCUE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_GOLFCLUB`, 0.0)
	SetWeaponDamageModifier(`WEAPON_BAT`, 0.0)
	SetWeaponDamageModifier(`WEAPON_KNIFE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_DAGGER`, 0.0)
	SetWeaponDamageModifier(`WEAPON_SWITCHBLADE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_REVOLVER`, 0.0)
	SetWeaponDamageModifier(`WEAPON_REVOLVER_MK2`, 0.0)
	SetWeaponDamageModifier(`WEAPON_MACHETE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_HATCHET`, 0.0)
	SetWeaponDamageModifier(`WEAPON_MICROSMG`, 0.0)
	SetWeaponDamageModifier(`WEAPON_MACHINEPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_MINISMG`, 0.0)
	SetWeaponDamageModifier(`WEAPON_ASSAULTSMG`, 0.0)
	SetWeaponDamageModifier(`WEAPON_SMG`, 0.0)
	SetWeaponDamageModifier(`WEAPON_SMG_MK2`, 0.0)
	SetWeaponDamageModifier(`WEAPON_COMBATPDW`, 0.0)
	SetWeaponDamageModifier(`WEAPON_GUSENBERG`, 0.0)
	SetWeaponDamageModifier(`WEAPON_VINTAGEPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_APPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_HEAVYPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_COMBATPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_VINTAGEPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_PISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_SNSPISTOL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_PISTOL_MK2`, 0.0)
  SetWeaponDamageModifier(`WEAPON_STUNGUN`, 0.0)
	SetWeaponDamageModifier(`WEAPON_SMOKEGRENADE`, 0.0)
	SetWeaponDamageModifier(`WEAPON_SNOWBALL`, 0.0)
	SetWeaponDamageModifier(`WEAPON_HIT_BY_WATER_CANNON`, 0.0)

	while true do
		Wait(0)
		SetPlayerHealthRechargeMultiplier(PlayerId(), 0.0)
		SetPedSuffersCriticalHits(PlayerPedId(), false)
	end
end)
